---
abstract: 'Wrap external command with a DWIM sub'
author:
  - 'Olivier Mengue <dolmen@cpan.org>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: System-Sub
requires:
  Carp: '0'
  File::Which: '0'
  IPC::Run: '0'
  Scalar::Util: '1.11'
  Sub::Name: '0'
  Symbol: '0'
  constant: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
version: '0.142280'
